version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quarkusdb
  stock-service:
    image: native/stock-service
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://db:5432/icoachconnect"
volumes:
  database-data: